#%RAML 1.0
title: Calculation

/calculationTraccia:
  get:
    queryParameters:
      destination:
        required: false
        enum:
           - SFO
           - LAX  
           - CLE
    responses:
      200:
        body:
          application/json:
            example: !include /example/response.raml
              